# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1369efdce3b040c3f244bd3226fd89db93433126b9a4e4979c4000aa9e749cf6e524c8f2f9c674a5918a78d3367f20aae9c812c7697e731e3cc80b381250cd9a
  devise_jwt_secret_key: 20e61bd4ce7e824a6e85b475b1cce4c0739fa77b7042c7de4a9336673e5b361a2493f55579cc88b59280333a18f6
  jwt_expiration_hours: 24

test:
  secret_key_base: 39c7826cf9ce9184d4a3283cb91e7d767302c248eac359ed6ff47f4c1059a50186a74e20dd936d1cb3405360cb5ef69b800972b416ef5f41ef66f0b459983538
  devise_jwt_secret_key: 20e61bd4ce7e824a6e85b475b1cce4c0739fa77b7042c7de4a9336673e5b361a2493f55579cc88b59280333a18f6
  jwt_expiration_hours: 1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  jwt_expiration_hours: 6
